### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by JavascriptFTW** [jdsutton/OnlineU#13]
I was trying to set up the project and got to making the `client_secrets.json` file. I am unclear as to how to proceed from here. I've tried my own client ID and it didn't work.

Any help would be appreciated.

**Comment by jdsutton** [comment]
Go to https://console.developers.google.com

Create a new project

Click "enable and manage APIs"

Click "credentials"

Create credentials --> OAuth client ID --> Web applications

Save the credentials file as `client_secrets.json` in the main directory.

Add your access point to the authorized javascript origins (your public IP, 127.0.0.1, localhost, etc). You can change this in project.py, a good addition might be adding an option to allow this to be set from the command line eg: python project.pi address=127.0.0.1

**Comment by jdsutton** [comment]
I will update the readme to reflect these instructions

**Comment by JavascriptFTW** [comment]
Okay, I've got almost everything working now except that whenever I try to log in the server gives an error `InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web"`. What should I set the `redirect_uris` property to to fix this?

**Comment by jdsutton** [comment]
Mine is: "redirect_uris":["http://www.example.com"]

You might have to set this in the developer console under "Authorized redirect URIs".

**Comment by jdsutton** [comment]
Thanks for testing all this out BTW it will help others in the future. Let me know when you get it working and I'll close this issue.
