### ISSUE TITLE
Run This Code

### ISSUE THREAD

**Issue by BlazeProgramming** [jdsutton/OnlineU#18]
What should I do to run the website offline? Head/block content/Python/AngularJS/Whateveritis is not working, giving me a blank and bad style, when I download the zip and open files.

**Comment by jdsutton** [comment]
Did you follow the instructions in the readme?

**Comment by BlazeProgramming** [comment]
I did, and it gave me an error. Let me bring it up.

**Comment by JavascriptFTW** [comment]
Perhaps you're using the wrong python version? That gave me some trouble when I was setting up.

**Comment by jdsutton** [comment]
It also sounds like you might be trying to directly open the HTML files. You should be running the server and then connecting to it. project.py will print out a line telling you the address of the server when you run it.

**Comment by BlazeProgramming** [comment]
It's rather odd, I have versions 2.3-2.9 I think (of Python).

I tried to start the server, but I got a couple of errors (but it may be my security config on my computer)

**Comment by jdsutton** [comment]
You may have more luck running the server on 127.0.0.1 than on 0.0.0.0. The most recent version of the code is set up to do this. I may be able to help more if you post the specific error.
