### ISSUE TITLE
.enrollButton is pushed off bottom edge of block

### ISSUE THREAD

**Issue by jdsutton** [jdsutton/OnlineU#34]
Enroll in a course to replicate this bug

**Comment by JavascriptFTW** [comment]
Could you please clarify what it is that's happening? Possibly post some screenshots? I can't seem to replicate this.

**Comment by jdsutton** [comment]
![bug image](http://i.imgur.com/m1O1kP0.png)

**Comment by jdsutton** [comment]
Bug is present in both Chrome and Firefox on Ubuntu 15.

**Comment by JavascriptFTW** [comment]
Thanks. I've found the problem now. A fix will be coming in shortly.
