### ISSUE TITLE
Style needs updating

### ISSUE THREAD

**Issue by jdsutton** [jdsutton/OnlineU#9]
The color scheme is not quite right and in general the site could be made to look more modern.
Here's a useful tool for building color palettes: http://paletton.com/

**Comment by JavascriptFTW** [comment]
Another useful site would be https://www.materialpalette.com/ if you like material design.

**Comment by BlazeProgramming** [comment]
Are these in styles.css?

I would also suggest getting a webfont. For now I'd look into Google Fonts, but for a long-term project it might be better to buy a font.

**Comment by jdsutton** [comment]
Yes, it's all in static/style.css.
